# Generated by Django 4.2.3 on 2023-07-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone_number', models.CharField(blank=True, default='', max_length=12)),
                ('consumer_number', models.IntegerField(db_index=True, unique=True)),
                ('user_role', models.CharField(choices=[('0', 'Staff'), ('1', 'Consumer')], default='0', max_length=1)),
                ('staff_id', models.CharField(blank=True, default='', max_length=10)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('otp', models.CharField(blank=True, default='', max_length=10)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('login_count', models.PositiveIntegerField(default=0)),
                ('failed_login_attempt', models.PositiveIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
